tests/e2e_test_auto_offer_on_device_rest.py

Two test files for the device client which will connect to a collab for placing offers and bids in the market.

TESTS-52: Test file for the device clients

---

tests/e2e_test_auto_offer_on_device_rest.py

Changing testing url from dev to staging for time being.

TESTS-52: Changing testing url from dev to staging

---

d3a_api_client/redis_aggregator.py
d3a_api_client/redis_client_base.py
d3a_api_client/redis_market.py
d3a_api_client/rest_device.py
d3a_api_client/rest_market.py
d3a_api_client/utils.py

Refactored the executor_function and made it reusable

Code refactoring , Executor function DRY

---

tests/e2e_test_auto_offer_on_device_rest.py

Adding the domain_name and websockets_domain_name as an argument. So, the trading script will not be dependent on particular testing enviroment

refactor_TESTS_52

---

d3a_api_client/redis_aggregator.py
d3a_api_client/redis_client_base.py
d3a_api_client/rest_device.py
d3a_api_client/utils.py
d3a_api_client/websocket_device.py
requirements/base.in
requirements/base.txt

Logged the progression of market cycles and ticks in a fancy table.
Data included : [ event, slot_completion, start_time , duration_min]

D3ASIM-3208: Added a market progression logging

---

cli.py
d3a_api_client/redis_aggregator.py
d3a_api_client/redis_client_base.py
d3a_api_client/redis_market.py
d3a_api_client/rest_device.py
d3a_api_client/rest_market.py
d3a_api_client/setups/auto_offer_bid_on_device.py
d3a_api_client/setups/test_redis_aggregator.py
d3a_api_client/utils.py
tox.ini

1. Removed the creation of extra loggers
2. Removed redundant loggings in events and logged them only in on_event_or_response
3. Added new events logger for the redis and rest markets
4. Removed redundant events loggings from redis market
5. Changed the default log level to ERROR
6. Errors handler improved format | select aggregator bug fix
7. Added extra logging to the trade /bids and offers events

Feature/D3ASIM-3199 Refactored the api client loggings

---

README.md
d3a_api_client/aggregator.py
d3a_api_client/commands.py
d3a_api_client/redis_aggregator.py
d3a_api_client/setups/test_ess_bid_redis_aggregator.py
d3a_api_client/setups/test_market_aggregator.py
d3a_api_client/setups/test_redis_aggregator.py
d3a_api_client/setups/test_redis_market_aggregator.py
integration_tests/test_aggregator_batch_commands.py

Added the market Batch commands functions + Adapted the setups using them

D3ASIM-3213: Added Market batch commands/ Adapted setups

---

README.md
d3a_api_client/aggregator.py
d3a_api_client/rest_device.py
d3a_api_client/utils.py

Create a method for `Aggregator` to reach the d3a-web endpoint for the aggregator's connected assets.

D3ASIM-3209: Endpoint for configuration's registry

---

d3a_api_client/redis_market.py
d3a_api_client/rest_device.py
d3a_api_client/setups/test_sending_energy_forecast.py

This change includes a homogenisation of the forecast unit and endpoint, which needs to be represented in the device_measurement_subscribers.

D3ASIM-3537: Added ability to send energy measurements.

---

d3a_api_client/redis_aggregator.py
d3a_api_client/redis_client_base.py
d3a_api_client/rest_device.py
d3a_api_client/utils.py
setup.py
tox.ini

We want to use this utility function both in the d3a-api-client and in the myco-api-client. Therefore, I'm moving it on d3a-interface.
This PR also allows to specify a different target branch for local tox tests.

D3ASIM-3572: show exceptions raised in threads

---

gsy_e_sdk/__init__.py
setup.cfg

Allow using bumpversion in this repository, without needing to manually add the tag.

Fix bumpversion replacement

---

gsy_e_sdk/__init__.py
setup.cfg

Bump version: 1.1.0 → 1.2.0

---

gsy_e_sdk/utils.py

The last commit is the actual feature change, other commits are refactoring ones

Feature/GSYE-105: Log the market type in log_bid_offer_confirmation

---

gsy_e_sdk/__init__.py
setup.cfg

Bump version to 1.3.0

---

tox.ini

Modularization of the testenvs in tox file was improved for gsy-web repository. The changes on this repo will match up with that done on gsy-web.
Improve the modularization of the tox configuration environments.

TESTS-143: I want to reduce tox files redundancy on tox file testenvs.

---

.github/pull_request_template.md
.github/workflows/development.yaml

Please describe what we want to achieve and why.
-

Added support for variable GSY_FRAMEWORK_BRANCH on the PR description.

---

.github/workflows/development.yaml

Some GSy repos presented a bug product of how the parsing of the branches specified on the PR message is done.
For this ticket, this workflow should be revised and fixed if needed.
- Fix on workflow step id.
- Fix variable validation on ci workflow by unquoting

TESTS-148: Review variable parsing form PR's body message

---

tox.ini

In past PRs regarding the integration tests execution workflow, some pending issues were pending to be addressed. This PR aims to further enhance the execution of the integration tests both from the dedicated repos and from GBIT.
- Add the rebuild flag option on tox.ini `integrationtests` testenv.
**INTEGRATION_TESTS_BRANCH**=TESTS-150

TESTS-150: Enhance integration tests execution workflow

---

gsy_e_sdk/setups/Asset_API_scripts/degrees_of_freedom.py
gsy_e_sdk/setups/Asset_API_scripts/resources/requirements.json

Need to implement simple example setups that only contain the bare minimum logic, in order to provide users with very straightforward examples and, at the same time, to create a sort of template that can be used to share bugs with the backend team.
Proposed a scripts that shows how to post a bid with requirements (on…
…ly via Redis connection). A JSON file has been also added where the list of requirements for each asset can be listed.

Degrees of freedom asset api refactoring

---

gsy_e_sdk/setups/Asset_API_scripts/redis_post_energy_deviations.py
gsy_e_sdk/setups/Asset_API_scripts/redis_settle_energy_deviations.py

Need to implement simple example setups that only contain the bare minimum logic, in order to provide users with very straightforward examples and, at the same time, to create a sort of template that can be used to share bugs with the backend team.
Proposed a script that would show how to post a bids and offers to the Settlement Market through Redis connection.

Settlement market asset api refactoring

---

.gitignore
fabfile.py
requirements/base.txt
requirements/dev.txt

Some dependencies are generating conflicts with gsy-framework.
- Bump dependencies

Fix dependencies

---

gsy_e_sdk/setups/asset_api_scripts/rest_basic_strategies.py

Fix issues on API template strategies for Storage assets. Previous strategy was not allowing proper rate updates for storages.
**INTEGRATION_TESTS_BRANCH**=PH-1131

PH-1131: Fix rest_basic_strategies for API Storage Strategies

---

.github/workflows/development.yaml
gsy_e_sdk/commands.py

Please describe what we want to achieve and why.
-
**INTEGRATION_TESTS_BRANCH**=bug/GSYE-513
**GSY_E_TARGET_BRANCH**=bug/GSYE-513

GSYE-513: Adapt commands to new offer/bid interfaces

---

gsy_e_sdk/cli.py

Please describe what we want to achieve and why.
-

Add ability to write logs to logfile
