- Dockerfile
- tox.ini
Updating the docker file to match the correct pip version for successfully buildling docker image to run d3a_api_client inside docker container.
> Docker File fix (pip version)

- README.md
- d3a_api_client/rest_device.py
- integration_tests/steps/market.py
- integration_tests/test_grid_fee.py
- mqtt_subscriber/oli_broker.py
- tests/test_sending_power_forecast.py
[Ticket](https://gridsingularity.atlassian.net/browse/D3ASIM-3066)
Changed `set_power_forecast` functions / endpoints to `set_energy_forecast` in `Oli_broker` and `api-client`
This is a sub PR related to D3A [Parent PR](https://github.com/gridsingularity/d3a/pull/1007)
> feature/D3ASIM-3066:change set_power_forecast to set_energy_forecast

- d3a_api_client/__init__.py
- d3a_api_client/redis_aggregator.py
- d3a_api_client/redis_client_base.py
- d3a_api_client/redis_device.py
- d3a_api_client/redis_market.py
- d3a_api_client/rest_market.py
- d3a_api_client/websocket_device.py
- integration_tests/device.feature
- integration_tests/steps/device.py
- integration_tests/test_pv_connection.py
Added a new callback function `on_event_or_response` to all Rest and Redis api devices.
This callback will be triggered upon receiving any message through the `Web socket` in the rest case or response received in a subscribed channel in the redis case.
Added an integration test to test if the current callback methods are also called + if the new callback is receiving all messages.
> feature/D3ASIM-3214: Added on_event_or_response callback

- d3a_api_client/setups/e2e_test_auto_offer_on_device_rest.py
Changing the data type of arguments : domain_name and websockets_domain_name. Earlier there data type was list now converting them into string.
> refactor_trading_script: Changing the data type of arguments

- d3a_api_client/rest_device.py
- d3a_api_client/utils.py
Two small fixed:
1. if autoregister is set to True in the RestClient, the wesocket should be established in order to receive the response of the d3a.
2. When there is a http response, there `resp.text` is not a dict, but only a string.
> D3ASIM-3325: Added small fixes.

- d3a_api_client/aggregator.py
- d3a_api_client/redis_aggregator.py
This is to be merged alongside #109 , #114 and other client PRs as they require adaptation from the used client scripts
> D3ASIM-3379: Deprecate old batch commands

- d3a_api_client/utils.py
The energy value should be displayed up to 3 decimal places in the logs which are generated by the `on_trade` method.
> Showing the energy value up to 3 decimal places in the logs.

- integration_tests/test_aggregator_batch_commands.py
The `original_bid_price` and `original_offer_price` keys in the `Bid` and `Offer` dataclasses have been recently renamed to `original_price`. This PR updates the code in this repo to reflect those changes.
- https://github.com/gridsingularity/d3a-interface/commit/7e41b3b5552be0617de98ed72c5b987c27239865
> fix bug with the original_price naming

- integration_tests/build_test_containers.sh
Integration tests were trying to delete a folder that was not being created anymore (because of the rebranding).
> Fix the name of the folder created for tests

- setup.py
- tox.ini
+ Add flake8 configurations in the `tox.ini` module to extend the max-line-length config to 99
>  Add d3a-api-client cli alias for backward compatibility

- README.md
- gsy_e_sdk/commands.py
- gsy_e_sdk/setups/asset_api_template.py
- gsy_e_sdk/setups/test_create_aggregator.py
- gsy_e_sdk/setups/test_ess_bid_redis_aggregator.py
- gsy_e_sdk/setups/test_redis_aggregator.py
- integration_tests/test_aggregator_batch_commands.py
- integration_tests/test_aggregator_ess.py
- integration_tests/test_aggregator_load.py
- integration_tests/test_aggregator_pv.py
I've left some methods out of the renaming because I suppose they can be called for both markets and assets (or only for markets). Let me know if they also need to be amended.
> D3ASIM-3553: Rename area_uuid parameters to asset_uuid

- integration_tests/steps/device.py
- integration_tests/test_aggregator_base.py
- integration_tests/test_aggregator_batch_commands.py
- integration_tests/test_aggregator_ess.py
- integration_tests/test_aggregator_load.py
- integration_tests/test_aggregator_market.py
- integration_tests/test_aggregator_pv.py
Errors occurring in integration tests are often just reported without enough detail about their content. This PR converts the bare count of errors with a list of error messages. This will provide some more information about each error.
> Improve test error logging

- gsy_e_sdk/setups/extract_area_uuid_from_area_name.py
- gsy_e_sdk/utils.py
Fix for 
```
11:27:30.529 ERROR    ( 236) sgqlc.endpoint.http           : GraphQL query failed with 1 errors
11:27:30.529 INFO     ( 243) sgqlc.endpoint.http           : Error #0:
11:27:30.529 INFO     ( 245) sgqlc.endpoint.http           :    | Syntax Error GraphQL (1:33) Unexpected character "'".
11:27:30.529 INFO     ( 245) sgqlc.endpoint.http           :    | 
11:27:30.529 INFO     ( 245) sgqlc.endpoint.http           :    | 1: query { readConfiguration(uuid: '{0ea147ea-0d04-4069-a64b-39c8c27c05c5}') { scenarioData { latest { serialized } } } }
11:27:30.529 INFO     ( 245) sgqlc.endpoint.http           :    |                                    ^
11:27:30.529 INFO     ( 245) sgqlc.endpoint.http           :    | 
11:27:30.529 INFO     ( 249) sgqlc.endpoint.http           :    - …
```
> Fix quote error in utils

- .github/pr_templates/pull_request_template.md
- .github/workflows/development.yaml
- tox.ini
Configure **gsy-e-sdk** workflow to call a particular `gsy-backend-integration-tests` branch on a PR.
GBIT repo’s tox file should be modified as well to support this possibility.
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-194
A template to the PR message should be added to help open source users to be aware of this.
> TESTS-135: I want to enable calls to a particular branch of GBIT on a PR on any involved repository.

- .github/pull_request_template.md
- .github/workflows/development.yaml
- tox.ini
- The migration of the integration tests to the current repository did not consider the need of creating a `gsy-e` image based on a particular branch when executing tests on gsy-myco-sdk and/or gsy-e-sdk, and therefore after the creation of a PR, the right image would not be built and tests would fail.
- Adapt PR template message to include the gsy-e TARGET_BRANCH that will be considered to build the docker image used by the tests.
- Adapt github actions to parse variable from PR body and pass it to the testenvs.
**INTEGRATION_TESTS_BRANCH**=TESTS-141
> TESTS-141: As gsy-backend-integration-tests, I want to build a docker image with the latest changes of the working branch

- gsy_e_sdk/redis_aggregator.py
- gsy_e_sdk/redis_client_base.py
- unit_tests/test_redis_aggregator.py
- unit_tests/test_redis_client_base.py
As `StrictRedis` class is deprecated, we decided to use `Redis` instead.
- Renaming all `StrictRedis` occurrences to `Redis`.
- Solving some styling issues.
> GSYE-165: Renamed 'StrictRedis' to 'Redis' as it is deprecated.

- gsy_e_sdk/cli.py
As described in [GSYE-274](https://gridsingularity.atlassian.net/browse/GSYE-274), we need to force the user to enter a valid setup name.
- Make --setup option required.
> GSYE-274: Make --setup a required CLI option with no default value.

- gsy_e_sdk/clients/rest_asset_client.py
- gsy_e_sdk/redis_aggregator.py
The `market` event is currently not being used to trigger the `on_market_slot` (nor the old `on_market_cycle`) method when Redis is running. 
- Call the new `on_market_slot` method when the `market` event is received.
- Call `on_market_cycle` (old alias for the new `on_market_slot`) when `on_market_slot` is called.
- #228 
---
> Fix on_market_slot event

- requirements/base.txt
- requirements/dev.txt
- Fix dependency name for backports-entry-points-selectable
**GSY_E_TARGET_BRANCH**=bug/GSYE-364
**GSY_FRAMEWORK_BRANCH**=bug/GSYE-364
> GSYE-364: Fix backports-entry-points-selectable==1.1.0 installation error

- gsy_e_sdk/clients/rest_asset_client.py
Please describe what we want to achieve and why.
-
> GSYE-803: Add set_live_generation to RestAssetClient
